version: "3"

volumes:
  mongodb_volume:

services:
  web:
    container_name: web
    build: project/server
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=EUROPE/KIEV
      - MONGO_DB_PORT=27017/
      - MONGO_DB_ADDR=mongodb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - worker
      - mongodb_container

  redis:
    image: redis
    ports:
      - '6379:6379'
    hostname: redis

  worker:
    build:
      context: project/server
    volumes:                                                                               #-
      - .:/usr/src/app
    hostname: worker
    entrypoint: celery
    command: -A tasks.celery worker -B --loglevel=info --logfile=project/logs/celery.log   #-

  mongodb_container:
    image: mongo:latest
    volumes:
    - mongodb_volume:/data/db
    ports:
    - '27017:27017'
    hostname: mongodb
